"""initial scans and findings tables

Revision ID: a3a496357a02
Revises: 
Create Date: 2026-08-24 15:56:22.530384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a496357a02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('modules', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_module', sa.String(length=120), nullable=False),
    sa.Column('modules_done', sa.Integer(), nullable=False),
    sa.Column('modules_total', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_status'), ['status'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('refs', sa.Text(), nullable=False),
    sa.Column('matched_at', sa.String(length=512), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_scan_id'))
        batch_op.drop_index(batch_op.f('ix_findings_module'))

    op.drop_table('findings')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_status'))
        batch_op.drop_index(batch_op.f('ix_scans_created_at'))

    op.drop_table('scans')
    # ### end Alembic commands ###
